<?php
/*!
 * Concerto 1.0 beta
 * http://themeconcert.com/concerto
 *
 * [WARNING]
 * This is restricted file and should not be modified in any way(unless you know what
 * you are doing). This file serves as the Base Class for setting up administration pages.
 */

require '../../../../../wp-config.php';

// Style Variables
$width = array(
		'container' => 960,
		'container-padding' => 10,
		'container-sidebar-divide' => 66,
		'content' => 580,
		'sidebar1' => 300,
		'sidebr2' => 0
	);

// Fixes
if (Concerto::config('design','columns') == 3) {
	$width['sidebar1'] = $width['sidebar2'] = 200;
	$width['container-sidebar-divide'] = 55;
	$width['content'] = 480;
}

// Display as a CSS file
header('Content-type: text/css');
?>
/**
 * This file was generated by Concerto <?php echo CONCERTO_VERSION . "\n"; ?>
 */
.container { width: <?php echo $width['container'] - ($width['container-padding'] * 2); ?>px; margin: 0 AUTO; padding: <?php echo $width['container-padding']; ?>px; }
.normal-page #main .container { background-position: <?php echo $width['container-sidebar-divide']; ?>%; }
.normal-page #content { width: <?php echo $width['content']; ?>px; }
.sidebars { width: <?php echo $width['sidebar1']; ?>px; }