<?php
/*!
 * Concerto 1.0 beta
 * http://themeconcert.com/concerto
 *
 * [WARNING]
 * This is restricted file and should not be modified in any way(unless you know what
 * you are doing). This file serves as the Base Class for setting up administration pages.
 */

require '../../../../../wp-config.php';

// Style Variables
$fonts = array(
		'base' => 'arial',
		'base-size' => 12,

		'content' => 'georgia',		
		'content-size' => 15,
		
		'menu' => 'inherit',
		'menu-size' => 12,
		
		'header' => 'inherit',
		'header-size' => 40,
		'tagline' => 'inherit',
		'tagline-size' => 14,
		
		'footer' => 'inherit',
		'footer-size' => 11,
	);

$colors = array(
		'site-background' => '#ffffff',
		'page-background' => '#ffffff',
		'border' => '#dddddd',
		
		'text' => '#000000',
		'link' => '#245cba',
		'link-visited' => '#8024ba',
		'link-hover' => '#245cba',
		
		'menu-link' => '#000000',
		'menu-link-hover' => '#000000',
		'menu-background' => '#ffffff',
		'menu-hover-background' => '#ffffff',
		'current-menu-background' => '#ffffff',
		'current-menu-link' => '#000000',
		'current-menu-link-hover' => '#000000',
		'menu-border' => '#eeeeee',
		'menu-hover-border' => '#dddddd',
		'current-menu-border' => '#dddddd',
		
		'header-background' => '#fdfdfd',
		'header' => '#000000',
		'header-hover' => '#245cba',
		'tagline' => '#666666',
		
		'footer-background' => '#fdfdfd',
		'footer' => '#666666',
	);

$borders = array(
		'menu-width' => '1',
	);

$width = array(
		'container' => 960,
		'container-padding' => 10,
		'container-sidebar-divide' => 66,
		
		'content' => 580,
		
		'sidebar1' => 300,
		'sidebr2' => 0
	);
	
$misc = array(
		'column-arrangement' => '1',

		'text-shadow-color' => '',
		'text-shadow-offset' => '',
		'border-layout' => '',
	);

// Fixes
if (Concerto::config('design','columns') == 3) {
	$width['sidebar1'] = $width['sidebar2'] = 200;
	$width['container-sidebar-divide'] = 55;
	$width['content'] = 480;
}

// Display as a CSS file
header('Content-type: text/css');
?>
/**
 * This file was generated by Concerto <?php echo CONCERTO_VERSION . "\n"; ?>
 */
body { font-family: arial, serif; background: <?php echo $colors['site-background']; ?>; color: <?php echo $colors['text-color']; ?>; font-size: 12px; line-height: 18px; }
a { color: <?php echo $colors['link']; ?>; }
a:visited { color: <?php echo $colors['link-visited']; ?>; }
a:hover { color: <?php echo $colors['link']; ?>; }

#header { border-bottom: 1px solid <?php echo $colors['border']; ?>; background: <?php echo $colors['header-background']; ?>; }
#footer { font-size: 11px; border-top: 1px solid <?php echo $colors['border']; ?>; background: <?php echo $colors['footer-background']; ?>; color: <?php echo $colors['footer']; ?>; }

.container { width: <?php echo $width['container'] - ($width['container-padding'] * 2); ?>px; margin: 0 AUTO; padding: <?php echo $width['container-padding']; ?>px; }
.normal-page #main .container { background-position: <?php echo $width['container-sidebar-divide']; ?>%; }
.normal-page #content { width: <?php echo $width['content']; ?>px; }
.sidebars { width: <?php echo $width['sidebar1']; ?>px; }

#branding h1#site-title { font-size: <?php echo $fonts['header-size']; ?>px; font-weight: bold; line-height: 150%; }
#branding h1#site-title a { color: <?php echo $colors['header']; ?>; }
#branding h1#site-title a:hover { color: <?php echo $colors['header-hover']; ?>; }
#branding p#site-description { font-size: <?php echo $fonts['tagline-size']; ?>px; color: <?php echo $colors['tagline']; ?>; }

#access .menu { width: <?php echo $width['container'] - ($width['container-padding'] * 2); ?>px; margin: 0 AUTO; padding: 0 <?php echo $width['container-padding']; ?>px; }
#access ul li a { font-size: <?php echo $fonts['menu-size']; ?>px; color: <?php echo $colors['menu-link']; ?>; background: <?php echo $colors['menu-background']; ?>; border: 1px solid <?php echo $colors['menu-border']; ?>; border-bottom: 1px solid <?php echo $colors['border']; ?>; }
#access ul li.current_page_item a, #access ul li.current_page_item a:hover { border: 1px solid <?php echo $colors['border']; ?>; border-bottom: 1px solid transparent; }
#access ul li a:hover, #access ul li a.active, #access ul li ul.children li a, #access ul li ul.children li a:hover { border-top: 1px solid <?php echo $colors['border']; ?>; }