<?php
/*!
 * Concerto 1.0 beta
 * http://themeconcert.com/concerto
 *
 * [WARNING]
 * This is restricted file and should not be modified in any way(unless you know what
 * you are doing). This file serves as the Base Class for setting up administration pages.
 */

require '../../../../../wp-config.php';

// Style Variables
$colors = Concerto::config('design','colors');
$fonts = Concerto::config('design','fonts');
$sizes = Concerto::config('design','sizes');
$borders = Concerto::config('design','borders');
$layout_columns_widths = Concerto::config('design','layout_columns_width');
$header = Concerto::config('design','header');
$bylines = Concerto::config('design','bylines');
$meta = Concerto::config('design','meta');
$posts = Concerto::config('design','posts');
$comments = Concerto::config('design','comments');

// Width Assignments
$width = array(
		'container' => ($layout_columns_widths['content'] + $layout_columns_widths['sidebar1'] + $layout_columns_widths['sidebar2']) + (Concerto::config('design','page_padding') * 4) + 40,
		'container-sidebar-divide' => floor($layout_columns_widths['content'] / Concerto::config('design','divide_factor')),
		'content' => $layout_columns_widths['content'],
		'sidebar1' => $layout_columns_widths['sidebar1'],
		'sidebr2' => $layout_columns_widths['sidebar2']
	);
	
// Font Assignments

// Border Assignments [header,footer,article,comment]

// Display as a CSS file
header('Content-type: text/css');
?>
/**
 * This file was generated by Concerto <?php echo CONCERTO_VERSION . "\n"; ?>
 */
body{cursor:default;font-family:arial, serif;background:<?php echo $colors['background']['site']; ?>;color:<?php echo $colors['fonts']['site']; ?>;font-size:<?php echo $sizes['body']; ?>px;line-height:<?php echo $sizes['body'] + 6; ?>px;}
#header{border-bottom:<?php echo $borders['header-bottom']; ?>px solid <?php echo $colors['borders']['common']; ?>;background:<?php echo $colors['background']['header']; ?>;}
#branding{padding:<?php echo Concerto::config('design','page_padding') + 50; ?>px <?php echo Concerto::config('design','page_padding'); ?>px <?php echo Concerto::config('design','page_padding') + 20; ?>px;}
#branding h1#site-title{font-size:<?php echo $sizes['header-title']; ?>px;}
#branding h1#site-title a{color:<?php echo $colors['fonts']['header-title']; ?>;}
#branding p#site-description{font-size:<?php echo $sizes['header-description']; ?>px;color:<?php echo $colors['fonts']['header-description']; ?>;}
#access{margin-bottom:-<?php echo $borders['menu']; ?>px;display:block;}
#access .menu{width:<?php echo $width['container'] - (Concerto::config('design','page_padding') * 2); ?>px;padding:0 <?php echo Concerto::config('design','page_padding'); ?>px;}
#access ul li a{color:<?php echo $colors['fonts']['menu']; ?>;background:<?php echo $colors['background']['menu']; ?>;border:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu']; ?>;border-bottom:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu-active']; ?>;}
#access ul li.current_page_item a,#access ul li.current_page_item a:hover{border:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu-active']; ?>;border-bottom:<?php echo $borders['menu']; ?>px solid transparent;}
#access ul li a:hover{border:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu-hover']; ?>;}
#access ul li a.active{border:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu-active']; ?>;border-bottom:<?php echo $borders['menu']; ?>px solid transparent;}
#access ul li ul.children{border:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu-active']; ?>;margin-top:-<?php echo $borders['menu']; ?>px;}
#access ul li ul.children li a{border-top:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu-active']; ?>;}
#access ul li ul.children li a:hover{border-top:<?php echo $borders['menu']; ?>px solid <?php echo $colors['borders']['menu-active']; ?>;}
.container { width: <?php echo $width['container']; ?>px; margin: 0 AUTO; padding: <?php echo Concerto::config('design','page_padding'); ?>px; }
.normal-page #main .container {background-position:<?php echo $width['container-sidebar-divide']; ?>%;}
.normal-page #content {width:<?php echo $width['content']; ?>px;}
.custom-page #content{padding:<?php echo Concerto::config('design','page_padding'); ?>px;}
#footer{font-size:<?php echo $sizes['footer']; ?>px;border-top:<?php echo $borders['footer-top']; ?>px solid <?php echo $colors['borders']['common']; ?>;background:<?php echo $colors['background']['footer']; ?>;color:<?php echo $colors['fonts']['footer']; ?>;}
.sidebars{width:<?php echo $width['sidebar1'] + $width['sidebar2']; ?>px;font-family:georgia, arial, serif;font-size:15px;line-height:22px;}

#content .entry-content a:visited{color:<?php echo $colors['fonts']['visited']; ?>;}